name: deploy

on:
  workflow_run:
    workflows: ["tests"]
    types: ["completed"]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/PotPulse && git pull origin main && node -v && whoami > ami.who && nvm use default && npm run build && php artisan optimize:clear
